apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-events
  namespace: argocd
  labels:
    project_name: argo-components  
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: argo-components
  source:
    path: charts/argo-events
    repoURL: https://github.com/argoproj/argo-helm.git
    targetRevision: HEAD
    helm:
      values: |
        configs:
          jetstream:
            versions:
            - version: "2.8.1"
              natsImage: nats:2.8.1
              metricsExporterImage: natsio/prometheus-nats-exporter:0.9.1
              configReloaderImage: natsio/nats-server-config-reloader:0.6.3
              startCommand: /nats-server
          nats:
            versions: 
            - version: 0.22.1
              natsStreamingImage: nats-streaming:0.22.1
              metricsExporterImage: natsio/prometheus-nats-exporter:0.9.3
  destination:
    namespace: argo-events
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
